import { readPsd } from 'ag-psd';
import { registerAsset } from './assets';
import { defaultAdjustments, type BlendMode, type CompositeDocument, type RasterLayer } from '../types/editor';

interface PsdLayerLike { name?: string; top?: number; left?: number; bottom?: number; right?: number; hidden?: boolean; opacity?: number; blendMode?: string; canvas?: HTMLCanvasElement | OffscreenCanvas; children?: PsdLayerLike[] }
interface PsdLike { width: number; height: number; canvas?: HTMLCanvasElement | OffscreenCanvas; children?: PsdLayerLike[] }
export interface ImportResult { document?: CompositeDocument; layers: RasterLayer[]; shouldReplaceProject: boolean }
export const SUPPORTED_IMPORT_EXTENSIONS = ['psd', 'png', 'jpg', 'jpeg', 'webp'] as const;
export function isSupportedImport(file: Pick<File, 'name' | 'type'>): boolean { const extension = file.name.toLowerCase().split('.').pop() ?? ''; if (!SUPPORTED_IMPORT_EXTENSIONS.includes(extension as (typeof SUPPORTED_IMPORT_EXTENSIONS)[number])) return false; if (!file.type || extension === 'psd') return true; const expected = extension === 'png' ? 'image/png' : extension === 'webp' ? 'image/webp' : 'image/jpeg'; return file.type === expected; }
const blendMap: Record<string, BlendMode> = { normal: 'source-over', darken: 'darken', multiply: 'multiply', colorburn: 'color-burn', linearburn: 'color-burn', lighten: 'lighten', screen: 'screen', colordodge: 'color-dodge', lineardodge: 'color-dodge', overlay: 'overlay', softlight: 'soft-light', hardlight: 'hard-light', difference: 'difference', exclusion: 'exclusion', hue: 'hue', saturation: 'saturation', color: 'color', luminosity: 'luminosity' };
const normalizeBlend = (value?: string): BlendMode => blendMap[value?.toLowerCase().replaceAll(/[^a-z]/g, '') ?? ''] ?? 'source-over';
const normalizeOpacity = (value?: number): number => value === undefined ? 100 : Math.round(Math.min(100, Math.max(0, value <= 1 ? value * 100 : value / 255 * 100)));
async function thumbnail(source: CanvasImageSource, width: number, height: number): Promise<string> { const size = 72, canvas = document.createElement('canvas'); canvas.width = size; canvas.height = size; const c = canvas.getContext('2d'); if (!c) return ''; const scale = Math.min(size / width, size / height), w = Math.max(1, width * scale), h = Math.max(1, height * scale); c.drawImage(source, (size - w) / 2, (size - h) / 2, w, h); return canvas.toDataURL('image/png'); }
async function makeLayer(source: CanvasImageSource, o: { name: string; sourcePath?: string; width: number; height: number; x: number; y: number; opacity?: number; visible?: boolean; blendMode?: BlendMode; scale?: number }): Promise<RasterLayer> { const id = crypto.randomUUID(), assetId = crypto.randomUUID(); registerAsset(assetId, source, o.width, o.height); return { id, assetId, name: o.name, sourcePath: o.sourcePath, width: o.width, height: o.height, thumbnailUrl: await thumbnail(source, o.width, o.height), visible: o.visible ?? true, locked: false, opacity: o.opacity ?? 100, blendMode: o.blendMode ?? 'source-over', transform: { x: o.x, y: o.y, scaleX: o.scale ?? 1, scaleY: o.scale ?? 1, rotation: 0 }, adjustments: defaultAdjustments() }; }
function flatten(children: PsdLayerLike[], parent: string[] = []): Array<{ layer: PsdLayerLike; path: string[] }> { const output: Array<{ layer: PsdLayerLike; path: string[] }> = []; for (const child of children) { const path = [...parent, child.name?.trim() || 'Unnamed layer']; if (child.children?.length) output.push(...flatten(child.children, path)); if (child.canvas) output.push({ layer: child, path }); } return output; }
async function importPsd(file: File, hasLayers: boolean): Promise<ImportResult> { const psd = readPsd(await file.arrayBuffer()) as unknown as PsdLike, documentModel = { name: file.name.replace(/\.psd$/i, ''), width: psd.width, height: psd.height, background: 'transparent' as const }, layers: RasterLayer[] = []; for (const { layer, path } of flatten(psd.children ?? []).reverse()) { if (!layer.canvas) continue; const left = layer.left ?? 0, top = layer.top ?? 0, width = Math.max(1, (layer.right ?? left + layer.canvas.width) - left), height = Math.max(1, (layer.bottom ?? top + layer.canvas.height) - top); layers.push(await makeLayer(await createImageBitmap(layer.canvas), { name: path.at(-1) ?? 'PSD layer', sourcePath: path.length > 1 ? path.slice(0, -1).join(' / ') : undefined, width, height, x: left, y: top, opacity: normalizeOpacity(layer.opacity), visible: !layer.hidden, blendMode: normalizeBlend(layer.blendMode) })); }
  if (!layers.length && psd.canvas) layers.push(await makeLayer(await createImageBitmap(psd.canvas), { name: documentModel.name, width: psd.width, height: psd.height, x: 0, y: 0 }));
  if (!layers.length) throw new Error('This PSD contains no readable raster or composite image data.'); return { document: hasLayers ? undefined : documentModel, layers, shouldReplaceProject: !hasLayers }; }
async function importImage(file: File, current: CompositeDocument, hasLayers: boolean): Promise<ImportResult> { const bitmap = await createImageBitmap(file), replace = !hasLayers, target = replace ? { name: file.name.replace(/\.[^.]+$/, ''), width: bitmap.width, height: bitmap.height, background: 'transparent' as const } : current, scale = replace ? 1 : Math.min(1, target.width / bitmap.width, target.height / bitmap.height); return { document: replace ? target : undefined, layers: [await makeLayer(bitmap, { name: file.name, width: bitmap.width, height: bitmap.height, x: (target.width - bitmap.width * scale) / 2, y: (target.height - bitmap.height * scale) / 2, scale })], shouldReplaceProject: replace }; }
export async function importFiles(files: File[], current: CompositeDocument, hasLayers: boolean): Promise<ImportResult[]> { const supported = files.filter(isSupportedImport); if (!supported.length) throw new Error('Choose a PSD, PNG, JPEG, or WebP file.'); const results: ImportResult[] = []; let active = current, projectHasLayers = hasLayers; for (const file of supported) { const result = file.name.toLowerCase().endsWith('.psd') ? await importPsd(file, projectHasLayers) : await importImage(file, active, projectHasLayers); results.push(result); projectHasLayers = true; if (result.document) active = result.document; } return results; }
