import { Link2, LoaderCircle, Sparkles } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { autoCompositeLabels, autoCompositeLayer, autoCompositePresets, pickSharedMatchAdjustments, type AutoCompositePreset, type AutoCompositeScope } from '../lib/autoComposite';
import { lightingPresetAdjustments, lightingPresetKeys, lightingPresetLabels, pickLightingAdjustments, type LightingPreset } from '../lib/lighting';
import { useEditorStore } from '../store/editorStore';
import { blendModes, defaultSceneLock, mvFinish, type BlendMode } from '../types/editor';

const blendLabels: Record<BlendMode, string> = { 'source-over': 'Normal', multiply: 'Multiply', screen: 'Screen', overlay: 'Overlay', 'soft-light': 'Soft Light', 'hard-light': 'Hard Light', 'color-dodge': 'Color Dodge', 'color-burn': 'Color Burn', darken: 'Darken', lighten: 'Lighten', difference: 'Difference', exclusion: 'Exclusion', hue: 'Hue', saturation: 'Saturation', color: 'Color', luminosity: 'Luminosity' };

export function AutoCompositeControls({ compact = false }: { compact?: boolean }) {
  const documentModel = useEditorStore((state) => state.document), layers = useEditorStore((state) => state.layers), selectedId = useEditorStore((state) => state.selectedLayerId), selected = layers.find((layer) => layer.id === selectedId);
  const patchLayer = useEditorStore((state) => state.patchLayer), patchAdjustments = useEditorStore((state) => state.patchLayerAdjustments), setSceneLock = useEditorStore((state) => state.setSceneLock), setFinish = useEditorStore((state) => state.setFinish), setMessage = useEditorStore((state) => state.setMessage), setError = useEditorStore((state) => state.setError);
  const [preset, setPreset] = useState<AutoCompositePreset>('balanced'), [referenceId, setReferenceId] = useState('backdrop'), [scope, setScope] = useState<AutoCompositeScope>('scene'), [busy, setBusy] = useState(false);
  const referenceLayers = useMemo(() => layers.filter((layer) => layer.kind !== 'group' && layer.id !== selectedId), [layers, selectedId]);
  const sceneLock = documentModel.sceneLock ?? defaultSceneLock();
  useEffect(() => { if (referenceId !== 'below' && referenceId !== 'backdrop' && !referenceLayers.some((layer) => layer.id === referenceId)) setReferenceId('backdrop'); }, [referenceId, referenceLayers]);
  if (!selected || selected.kind === 'group' || !selectedId) return null;
  const run = async () => {
    setBusy(true); setError(null); setMessage(`Analyzing ${selected.name} against ${referenceId === 'below' ? 'the composite below' : referenceId === 'backdrop' ? 'the backdrop' : 'the reference layer'}…`);
    await new Promise<void>((resolve) => setTimeout(resolve, 20));
    try {
      const generated = autoCompositeLayer(documentModel, layers, selected, preset, referenceId, scope), lockActive = sceneLock.enabled && scope === 'scene';
      const lockMatches = lockActive && sceneLock.adjustments && sceneLock.preset === preset && sceneLock.referenceId === referenceId && sceneLock.scope === scope;
      const sharedMatch = lockMatches ? sceneLock.adjustments : pickSharedMatchAdjustments(generated);
      if (lockActive && !lockMatches) setSceneLock({ enabled: true, preset, referenceId, scope, sourceLayerId: selectedId, sourceLayerName: selected.name, adjustments: sharedMatch });
      patchAdjustments(selectedId, { ...generated, ...(lockActive ? sharedMatch : {}), ...pickLightingAdjustments(selected.adjustments) });
      if (documentModel.finish.diffusion === 0 && documentModel.finish.bloom === 0 && documentModel.finish.vignette === 0) setFinish(mvFinish());
      setMessage(lockActive ? `${autoCompositeLabels[preset]} applied with shared Scene Lock` : `${autoCompositeLabels[preset]} adaptive auto composite applied`);
    }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'Auto composite failed.'); setMessage('Auto composite could not be applied'); }
    finally { setBusy(false); }
  };
  const resetSceneLock = () => { setSceneLock({ preset: null, referenceId: null, scope: null, sourceLayerId: null, sourceLayerName: null, adjustments: null }); setMessage('Scene Lock will be rebuilt by the next Auto'); };
  const lockReady = Boolean(sceneLock.adjustments), lockStatus = lockReady ? `Shared from ${sceneLock.sourceLayerName ?? 'a character'}` : 'First Auto sets the shared grade';
  const referenceOptions = <><option value="backdrop">Backdrop — bottom visible layer</option><option value="below">Composite below selected layer</option>{referenceLayers.map((layer) => <option key={layer.id} value={layer.id}>{layer.name}</option>)}</>;
  if (compact) return <div className="quick-composite"><label><span>Blend</span><select value={selected.blendMode} onChange={(event) => patchLayer(selectedId, { blendMode: event.currentTarget.value as BlendMode })}>{blendModes.map((mode) => <option key={mode} value={mode}>{blendLabels[mode]}</option>)}</select></label><label><span>Ref</span><select aria-label="Match against" value={referenceId} onChange={(event) => setReferenceId(event.currentTarget.value)}>{referenceOptions}</select></label><label><span>Lock</span><button className={`quick-composite__lock ${sceneLock.enabled ? 'is-active' : ''}`} type="button" onClick={() => setSceneLock({ enabled: !sceneLock.enabled })}><Link2 size={12}/>{sceneLock.enabled ? lockReady ? 'Locked' : 'On — set next' : 'Adaptive'}</button></label><label><span>Light</span><select aria-label="Creative lighting preset" value="" onChange={(event) => { const value = event.currentTarget.value as LightingPreset | ''; if (value) { patchAdjustments(selectedId, lightingPresetAdjustments(value)); setMessage(`${lightingPresetLabels[value]} lighting applied`); } }}><option value="">Choose lighting…</option>{lightingPresetKeys.map((value) => <option key={value} value={value}>{lightingPresetLabels[value]}</option>)}</select></label><div className="quick-composite__auto quick-composite__auto--scoped"><select aria-label="Auto composite preset" value={preset} onChange={(event) => setPreset(event.currentTarget.value as AutoCompositePreset)}>{autoCompositePresets.map((value) => <option key={value} value={value}>{autoCompositeLabels[value]}</option>)}</select><select aria-label="Lighting sample" value={scope} onChange={(event) => setScope(event.currentTarget.value as AutoCompositeScope)}><option value="scene">Scene</option><option value="local">Local</option></select><button type="button" disabled={busy} onClick={() => void run()}>{busy ? <LoaderCircle className="spin" size={13}/> : <Sparkles size={13}/>}Auto</button></div></div>;
  return <section className="inspector-section auto-composite"><div className="section-title-row"><h3>Auto Composite</h3><Sparkles size={14}/></div><label className="select-field"><span>Match against</span><select value={referenceId} onChange={(event) => setReferenceId(event.currentTarget.value)}>{referenceOptions}</select></label><label className="select-field"><span>Lighting sample</span><select value={scope} onChange={(event) => setScope(event.currentTarget.value as AutoCompositeScope)}><option value="scene">Whole reference — consistent characters</option><option value="local">Area behind subject — local lighting</option></select></label><div className="scene-lock-row"><label><input type="checkbox" checked={sceneLock.enabled} onChange={(event) => setSceneLock({ enabled: event.currentTarget.checked })}/><Link2 size={13}/><span>Scene Lock</span></label><button type="button" disabled={!lockReady} onClick={resetSceneLock}>Rebuild</button></div><p className={`scene-lock-status ${lockReady ? 'is-ready' : ''}`}>{sceneLock.enabled ? lockStatus : 'Adaptive matching — each character is analyzed separately'}</p><div className="preset-grid">{autoCompositePresets.map((value) => <button className={preset === value ? 'is-active' : ''} type="button" key={value} onClick={() => setPreset(value)}>{autoCompositeLabels[value]}</button>)}</div><button className="auto-composite__run" type="button" disabled={busy} onClick={() => void run()}>{busy ? <LoaderCircle className="spin" size={15}/> : <Sparkles size={15}/>}Analyze & match</button><p className="inspector-note">Scene Lock shares the scene grade across characters. Inner wrap uses the actual backdrop pixels per character; edge softness and contact shadows remain size-aware. The first Auto also adds a restrained global MV Finish.</p></section>;
}
