import { BrainCircuit, LoaderCircle, RotateCcw, ScanLine } from 'lucide-react';
import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import { getAsset } from '../lib/assets';
import { generateAiDepthMap, generateFastDepthMap, type DepthProgress } from '../lib/depthEstimation';
import { useEditorStore } from '../store/editorStore';
import { defaultDepthOfField } from '../types/editor';
import { RangeField } from './RangeField';

function DepthPreview({ assetId, invert, onFocus }: { assetId: string; invert: boolean; onFocus: (focus: number) => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    const asset = getAsset(assetId), canvas = canvasRef.current; if (!asset || !canvas) return;
    const scale = Math.min(1, 280 / asset.width), width = Math.max(1, Math.round(asset.width * scale)), height = Math.max(1, Math.round(asset.height * scale)); canvas.width = width; canvas.height = height;
    const context = canvas.getContext('2d', { willReadFrequently: true }); if (!context) return; context.filter = invert ? 'invert(1)' : 'none'; context.drawImage(asset.source, 0, 0, width, height); context.filter = 'none';
  }, [assetId, invert]);
  const pick = (event: ReactPointerEvent<HTMLButtonElement>) => { const canvas = canvasRef.current, context = canvas?.getContext('2d', { willReadFrequently: true }); if (!canvas || !context) return; const rect = canvas.getBoundingClientRect(), x = Math.max(0, Math.min(canvas.width - 1, Math.floor((event.clientX - rect.left) / rect.width * canvas.width))), y = Math.max(0, Math.min(canvas.height - 1, Math.floor((event.clientY - rect.top) / rect.height * canvas.height))); onFocus(Math.round((context.getImageData(x, y, 1, 1).data[0] ?? 0) / 255 * 100)); };
  return <button className="depth-preview" type="button" onPointerDown={pick} title="Click a point that should stay in focus"><canvas ref={canvasRef}/><span>Click the distance to keep sharp</span></button>;
}

export function DepthOfFieldControls() {
  const selectedId = useEditorStore((state) => state.selectedLayerId), layers = useEditorStore((state) => state.layers), layer = layers.find((candidate) => candidate.id === selectedId);
  const patch = useEditorStore((state) => state.patchLayerDepthOfField), setMessage = useEditorStore((state) => state.setMessage), setError = useEditorStore((state) => state.setError);
  const [busy, setBusy] = useState(false), [progress, setProgress] = useState<DepthProgress | null>(null);
  if (!selectedId || !layer || layer.kind === 'group') return null;
  const settings = { ...defaultDepthOfField(), ...layer.depthOfField }, backdrop = layers.find((candidate) => candidate.kind !== 'group' && candidate.visible);
  const generate = async (method: 'ai' | 'fast') => { setBusy(true); setError(null); setProgress(method === 'ai' ? { phase: 'loading', progress: null, message: 'Preparing local depth estimation…' } : { phase: 'processing', progress: null, message: 'Building a fast perspective map…' }); try { const result = method === 'ai' ? await generateAiDepthMap(layer.assetId, setProgress) : await generateFastDepthMap(layer.assetId); patch(selectedId, { enabled: true, depthMapAssetId: result.assetId, method: result.method }); setMessage(method === 'ai' ? 'AI depth map generated locally' : 'Fast approximate depth map generated'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Depth estimation failed.'); setMessage('Depth map could not be generated'); } finally { setBusy(false); setProgress(null); } };
  if (backdrop?.id !== selectedId) return <section className="inspector-section depth-controls"><div className="section-title-row"><h3>Scene layer depth</h3><button className="text-button" type="button" onClick={() => patch(selectedId, { sceneDepth: null })}><RotateCcw size={13}/>Auto</button></div>{!backdrop?.depthOfField?.depthMapAssetId ? <p className="depth-warning">Generate a depth map on the bottom backdrop first.</p> : null}<label className="toggle-row"><input type="checkbox" checked={settings.sceneDepth === null} onChange={(event) => patch(selectedId, { sceneDepth: event.currentTarget.checked ? null : 55 })}/><span>Auto from backdrop</span><small>samples the feet</small></label>{settings.sceneDepth !== null ? <RangeField label="Layer distance" value={settings.sceneDepth} min={0} max={100} unit="%" onChange={(sceneDepth) => patch(selectedId, { sceneDepth })} onReset={() => patch(selectedId, { sceneDepth: null })}/> : null}<p className="inspector-note">Scene DoF composites every visible layer first, then applies one shared blur. Layers at the same distance now receive the same blur kernel; set a manual distance only when the automatic contact-point sample is wrong.</p></section>;
  return <section className="inspector-section depth-controls"><div className="section-title-row"><h3>Scene depth &amp; DoF</h3><button className="text-button" type="button" onClick={() => patch(selectedId, defaultDepthOfField())}><RotateCcw size={13}/>Reset</button></div><div className="depth-actions"><button className="depth-actions__primary" type="button" disabled={busy} onClick={() => void generate('ai')}>{busy ? <LoaderCircle className="spin" size={14}/> : <BrainCircuit size={14}/>}AI depth</button><button type="button" disabled={busy} onClick={() => void generate('fast')}><ScanLine size={14}/>Fast map</button></div>{progress ? <div className="depth-progress"><span>{progress.message}</span>{progress.progress !== null ? <progress max="100" value={progress.progress}/> : <span className="depth-progress__track"/>}</div> : null}{settings.depthMapAssetId ? <><DepthPreview assetId={settings.depthMapAssetId} invert={settings.invert} onFocus={(focus) => patch(selectedId, { focus })}/><label className="toggle-row"><input type="checkbox" checked={settings.enabled} onChange={(event) => patch(selectedId, { enabled: event.currentTarget.checked })}/><span>Enable Scene DoF</span><small>{settings.method === 'ai' ? 'AI map' : 'Fast estimate'}</small></label><RangeField label="Focus distance" value={settings.focus} min={0} max={100} unit="%" onChange={(focus) => patch(selectedId, { focus })} onReset={() => patch(selectedId, { focus: defaultDepthOfField().focus })}/><RangeField label="Focus range" value={settings.focusRange} min={0} max={60} unit="%" onChange={(focusRange) => patch(selectedId, { focusRange })} onReset={() => patch(selectedId, { focusRange: defaultDepthOfField().focusRange })}/><RangeField label="Maximum blur" value={settings.maxBlur} min={0} max={60} step={.5} unit=" px" onChange={(maxBlur) => patch(selectedId, { maxBlur })} onReset={() => patch(selectedId, { maxBlur: defaultDepthOfField().maxBlur })}/><label className="toggle-row"><input type="checkbox" checked={settings.invert} onChange={(event) => patch(selectedId, { invert: event.currentTarget.checked })}/><span>Invert near / far</span></label></> : null}<p className="inspector-note">Scene DoF flattens the visible composite and applies one continuous depth blur, so backgrounds and characters share the same optical response. AI depth runs locally in this browser; the image is never uploaded.</p></section>;
}
