import { ImagePlus, MousePointer2, ShieldCheck } from 'lucide-react';
import { useCallback, useEffect, useLayoutEffect, useRef, useState, type PointerEvent as ReactPointerEvent, type WheelEvent as ReactWheelEvent } from 'react';
import { fitZoom, layerCenter, layerHandles, nearestTransformHandle, pointInsideLayer, screenToDocument, type Point } from '../lib/geometry';
import { drawComposition, drawDocumentSurface, hasCompositeFinish, isLayerEffectivelyVisible, renderPreviewComposition } from '../lib/renderer';
import { useEditorStore } from '../store/editorStore';
import { defaultAdjustments, defaultDepthOfField, defaultFinish, type RasterLayer } from '../types/editor';

interface Props { fitSignal: number; onFiles: (files: File[]) => void; onImport: () => void; onSaveProject: () => void; onOpenProject: () => void }
type DragState =
  | { kind: 'pan'; pointerId: number; startScreen: Point; startPan: Point }
  | { kind: 'move'; pointerId: number; layerId: string; startDocument: Point; startPosition: Point }
  | { kind: 'scale'; pointerId: number; layerId: string; center: Point; startDistance: number; startScale: Point }
  | { kind: 'rotate'; pointerId: number; layerId: string; center: Point; startAngle: number; startRotation: number };
const clampZoom = (value: number) => Math.min(8, Math.max(.05, value));
const isInput = (target: EventTarget | null) => target instanceof HTMLInputElement || target instanceof HTMLTextAreaElement || target instanceof HTMLSelectElement || (target instanceof HTMLElement && target.isContentEditable);

export function EditorCanvas({ fitSignal, onFiles, onImport, onSaveProject, onOpenProject }: Props) {
  const shellRef = useRef<HTMLDivElement>(null), canvasRef = useRef<HTMLCanvasElement>(null), dragRef = useRef<DragState | null>(null), spaceRef = useRef(false);
  const [size, setSize] = useState({ width: 1, height: 1 }), [fileHover, setFileHover] = useState(false), [interacting, setInteracting] = useState(false);
  const documentModel = useEditorStore((s) => s.document), layers = useEditorStore((s) => s.layers), selectedId = useEditorStore((s) => s.selectedLayerId), viewport = useEditorStore((s) => s.viewport), tool = useEditorStore((s) => s.tool), compare = useEditorStore((s) => s.compareBefore);
  const select = useEditorStore((s) => s.selectLayer), patchTransform = useEditorStore((s) => s.patchLayerTransform), remove = useEditorStore((s) => s.removeLayer), duplicate = useEditorStore((s) => s.duplicateLayer), setViewport = useEditorStore((s) => s.setViewport), setTool = useEditorStore((s) => s.setTool), setCompare = useEditorStore((s) => s.setCompareBefore), undo = useEditorStore((s) => s.undo), redo = useEditorStore((s) => s.redo), beginTransaction = useEditorStore((s) => s.beginTransaction), endTransaction = useEditorStore((s) => s.endTransaction);
  const fit = useCallback(() => setViewport({ zoom: fitZoom(size, documentModel), panX: 0, panY: 0 }), [documentModel, setViewport, size]);

  useLayoutEffect(() => { const shell = shellRef.current; if (!shell) return; const observer = new ResizeObserver(([entry]) => entry && setSize({ width: Math.max(1, entry.contentRect.width), height: Math.max(1, entry.contentRect.height) })); observer.observe(shell); return () => observer.disconnect(); }, []);
  useEffect(() => { fit(); }, [fitSignal, documentModel.width, documentModel.height, size.width, size.height, fit]);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const dpr = window.devicePixelRatio || 1; canvas.width = Math.round(size.width * dpr); canvas.height = Math.round(size.height * dpr); const context = canvas.getContext('2d'); if (!context) return; const frame = requestAnimationFrame(() => { context.setTransform(dpr, 0, 0, dpr, 0, 0); context.clearRect(0, 0, size.width, size.height); context.fillStyle = '#17191f'; context.fillRect(0, 0, size.width, size.height); context.imageSmoothingEnabled = true; context.imageSmoothingQuality = 'high'; context.save(); context.translate(size.width / 2 + viewport.panX, size.height / 2 + viewport.panY); context.scale(viewport.zoom, viewport.zoom); context.translate(-documentModel.width / 2, -documentModel.height / 2); drawDocumentSurface(context, documentModel); const displayLayers = compare ? layers.map((layer) => layer.kind === 'group' ? layer : ({ ...layer, adjustments: defaultAdjustments(), depthOfField: defaultDepthOfField() })) : layers, displayDocument = compare ? { ...documentModel, finish: defaultFinish() } : documentModel; if (hasCompositeFinish(displayDocument.finish)) { const preview = renderPreviewComposition(displayDocument, displayLayers); context.drawImage(preview, 0, 0, documentModel.width, documentModel.height); } else drawComposition(context, displayDocument, displayLayers); const selected = layers.find((layer) => layer.id === selectedId); if (selected && selected.kind !== 'group' && isLayerEffectivelyVisible(selected, layers)) drawSelection(context, selected, viewport.zoom); context.restore(); }); return () => cancelAnimationFrame(frame); }, [compare, documentModel, layers, selectedId, size, viewport]);

  useEffect(() => { const down = (event: KeyboardEvent) => { if (isInput(event.target)) return; const command = event.ctrlKey || event.metaKey; if (command && event.key.toLowerCase() === 'z') { event.preventDefault(); if (event.shiftKey) redo(); else undo(); return; } if (command && event.key.toLowerCase() === 'y') { event.preventDefault(); redo(); return; } if (command && event.key.toLowerCase() === 's') { event.preventDefault(); onSaveProject(); return; } if (command && event.key.toLowerCase() === 'o') { event.preventDefault(); onOpenProject(); return; } if (command && event.key.toLowerCase() === 'd' && selectedId) { event.preventDefault(); duplicate(selectedId); return; } if (event.code === 'Space') { spaceRef.current = true; event.preventDefault(); } if (event.key.toLowerCase() === 'v') setTool('move'); if (event.key.toLowerCase() === 'h') setTool('hand'); if (event.key.toLowerCase() === 'b' && layers.length) setCompare(!compare); if (event.key === '0') fit(); if ((event.key === 'Delete' || event.key === 'Backspace') && selectedId) { event.preventDefault(); remove(selectedId); } if (selectedId && ['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)) { const layer = useEditorStore.getState().layers.find((l) => l.id === selectedId); if (!layer || layer.locked) return; event.preventDefault(); const amount = event.shiftKey ? 10 : 1, next = { x: layer.transform.x, y: layer.transform.y }; if (event.key === 'ArrowLeft') next.x -= amount; if (event.key === 'ArrowRight') next.x += amount; if (event.key === 'ArrowUp') next.y -= amount; if (event.key === 'ArrowDown') next.y += amount; patchTransform(selectedId, next); } }; const up = (event: KeyboardEvent) => { if (event.code === 'Space') spaceRef.current = false; }; const paste = (event: ClipboardEvent) => { const files = Array.from(event.clipboardData?.files ?? []).filter((file) => file.type.startsWith('image/')); if (files.length) { event.preventDefault(); onFiles(files); } }; window.addEventListener('keydown', down); window.addEventListener('keyup', up); window.addEventListener('paste', paste); return () => { window.removeEventListener('keydown', down); window.removeEventListener('keyup', up); window.removeEventListener('paste', paste); }; }, [compare, duplicate, fit, layers.length, onFiles, onOpenProject, onSaveProject, patchTransform, redo, remove, selectedId, setCompare, setTool, undo]);

  const canvasPoint = (event: { clientX: number; clientY: number }): Point => { const rect = canvasRef.current?.getBoundingClientRect(); return { x: event.clientX - (rect?.left ?? 0), y: event.clientY - (rect?.top ?? 0) }; };
  const pointerDown = (event: ReactPointerEvent<HTMLCanvasElement>) => { if (![0,1].includes(event.button)) return; const screen = canvasPoint(event); if (event.button === 1 || tool === 'hand' || spaceRef.current) { dragRef.current = { kind: 'pan', pointerId: event.pointerId, startScreen: screen, startPan: { x: viewport.panX, y: viewport.panY } }; event.currentTarget.setPointerCapture(event.pointerId); setInteracting(true); return; } const point = screenToDocument(screen, size, documentModel, viewport), selected = layers.find((l) => l.id === selectedId && l.kind !== 'group'); if (selected && !selected.locked) { const handle = nearestTransformHandle(point, selected, viewport.zoom); if (handle) { const center = layerCenter(selected); beginTransaction(); dragRef.current = handle === 'scale' ? { kind: 'scale', pointerId: event.pointerId, layerId: selected.id, center, startDistance: Math.max(.001, Math.hypot(point.x - center.x, point.y - center.y)), startScale: { x: selected.transform.scaleX, y: selected.transform.scaleY } } : { kind: 'rotate', pointerId: event.pointerId, layerId: selected.id, center, startAngle: Math.atan2(point.y - center.y, point.x - center.x), startRotation: selected.transform.rotation }; event.currentTarget.setPointerCapture(event.pointerId); setInteracting(true); return; } } const hit = [...layers].reverse().find((layer) => layer.kind !== 'group' && isLayerEffectivelyVisible(layer, layers) && pointInsideLayer(point, layer)); if (!hit) { select(null); return; } select(hit.id); if (hit.locked) return; beginTransaction(); dragRef.current = { kind: 'move', pointerId: event.pointerId, layerId: hit.id, startDocument: point, startPosition: { x: hit.transform.x, y: hit.transform.y } }; event.currentTarget.setPointerCapture(event.pointerId); setInteracting(true); };
  const pointerMove = (event: ReactPointerEvent<HTMLCanvasElement>) => { const drag = dragRef.current; if (!drag || drag.pointerId !== event.pointerId) return; const screen = canvasPoint(event); if (drag.kind === 'pan') { setViewport({ panX: drag.startPan.x + screen.x - drag.startScreen.x, panY: drag.startPan.y + screen.y - drag.startScreen.y }); return; } const point = screenToDocument(screen, size, documentModel, viewport); if (drag.kind === 'move') patchTransform(drag.layerId, { x: drag.startPosition.x + point.x - drag.startDocument.x, y: drag.startPosition.y + point.y - drag.startDocument.y }); if (drag.kind === 'scale') { const factor = Math.max(.01, Math.hypot(point.x - drag.center.x, point.y - drag.center.y) / drag.startDistance), scaleX = drag.startScale.x * factor, scaleY = drag.startScale.y * factor, layer = useEditorStore.getState().layers.find((l) => l.id === drag.layerId); if (layer) patchTransform(drag.layerId, { scaleX, scaleY, x: drag.center.x - layer.width * scaleX / 2, y: drag.center.y - layer.height * scaleY / 2 }); } if (drag.kind === 'rotate') { const angle = Math.atan2(point.y - drag.center.y, point.x - drag.center.x); patchTransform(drag.layerId, { rotation: drag.startRotation + (angle - drag.startAngle) * 180 / Math.PI }); } };
  const pointerFinish = (event: ReactPointerEvent<HTMLCanvasElement>) => { if (dragRef.current?.pointerId !== event.pointerId) return; if (dragRef.current.kind !== 'pan') endTransaction(); dragRef.current = null; setInteracting(false); if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); };
  const wheel = (event: ReactWheelEvent<HTMLCanvasElement>) => { event.preventDefault(); const screen = canvasPoint(event), point = screenToDocument(screen, size, documentModel, viewport), zoom = clampZoom(viewport.zoom * Math.exp(-event.deltaY * .0015)); setViewport({ zoom, panX: screen.x - size.width / 2 - (point.x - documentModel.width / 2) * zoom, panY: screen.y - size.height / 2 - (point.y - documentModel.height / 2) * zoom }); };
  return <main ref={shellRef} className={`canvas-shell ${fileHover ? 'is-file-hover' : ''}`} onDragEnter={(e) => { e.preventDefault(); setFileHover(true); }} onDragOver={(e) => e.preventDefault()} onDragLeave={(e) => { if (e.currentTarget === e.target) setFileHover(false); }} onDrop={(e) => { e.preventDefault(); setFileHover(false); onFiles(Array.from(e.dataTransfer.files)); }}><canvas ref={canvasRef} className={`editor-canvas tool-${tool} ${interacting ? 'is-interacting' : ''}`} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerFinish} onPointerCancel={pointerFinish} onWheel={wheel} onContextMenu={(e) => e.preventDefault()}/>{!layers.length ? <div className="empty-canvas"><div className="empty-canvas__icon"><MousePointer2 size={24}/></div><h1>Composite existing pixels.</h1><p>Drop PSD, PNG, JPEG, or WebP files. Everything stays in this browser.</p><button className="toolbar-button primary" type="button" onClick={onImport}><ImagePlus size={17}/>Import artwork</button><span><ShieldCheck size={13}/>No upload. No image regeneration.</span></div> : null}{fileHover ? <div className="drop-overlay"><ImagePlus size={30}/><strong>Drop to import</strong><span>PSD · PNG · JPEG · WebP</span></div> : null}</main>;
}

function drawSelection(context: CanvasRenderingContext2D, layer: RasterLayer, zoom: number) { const { corners, rotation, top } = layerHandles(layer, 34 / zoom); context.save(); context.globalCompositeOperation = 'source-over'; context.strokeStyle = '#8bb4ff'; context.fillStyle = '#e8f0ff'; context.lineWidth = 1.5 / zoom; context.setLineDash([6 / zoom, 4 / zoom]); context.beginPath(); context.moveTo(corners[0]?.x ?? 0, corners[0]?.y ?? 0); for (const point of corners.slice(1)) context.lineTo(point.x, point.y); context.closePath(); context.stroke(); context.setLineDash([]); context.beginPath(); context.moveTo(top.x, top.y); context.lineTo(rotation.x, rotation.y); context.stroke(); const radius = 5.5 / zoom; for (const point of corners) { context.beginPath(); context.rect(point.x - radius, point.y - radius, radius * 2, radius * 2); context.fill(); context.stroke(); } context.beginPath(); context.arc(rotation.x, rotation.y, radius, 0, Math.PI * 2); context.fill(); context.stroke(); context.restore(); }
