import { Sparkles, RotateCcw } from 'lucide-react';
import { useEditorStore } from '../store/editorStore';
import { defaultFinish, mvFinish } from '../types/editor';
import { RangeField } from './RangeField';

export function FinishingControls() {
  const storedFinish = useEditorStore((state) => state.document.finish), setFinish = useEditorStore((state) => state.setFinish), setMessage = useEditorStore((state) => state.setMessage);
  const finish = { ...defaultFinish(), ...storedFinish };
  const reset = () => { setFinish(defaultFinish()); setMessage('Global finish reset'); };
  return <section className="inspector-section finishing-controls"><div className="section-title-row"><h3>Global Adjustment</h3><button className="text-button" type="button" onClick={reset}><RotateCcw size={13}/>Reset</button></div><div className="finish-presets"><button type="button" onClick={() => { setFinish(mvFinish()); setMessage('MV Finish applied globally'); }}><Sparkles size={13}/>MV Finish</button><button type="button" onClick={() => { setFinish({ diffusion: 30, diffusionRadius: 32, bloom: 16, bloomRadius: 48, vignette: 10 }); setMessage('Dreamy finish applied globally'); }}>Dreamy</button><button type="button" onClick={reset}>Clean</button></div><RangeField label="Diffusion" value={finish.diffusion} min={0} max={100} unit="%" onChange={(diffusion) => setFinish({ diffusion })} onReset={() => setFinish({ diffusion: 0 })}/><RangeField label="Diffusion radius" value={finish.diffusionRadius} min={2} max={80} step={.5} unit=" px" onChange={(diffusionRadius) => setFinish({ diffusionRadius })} onReset={() => setFinish({ diffusionRadius: defaultFinish().diffusionRadius })}/><RangeField label="Highlight bloom" value={finish.bloom} min={0} max={100} unit="%" onChange={(bloom) => setFinish({ bloom })} onReset={() => setFinish({ bloom: 0 })}/><RangeField label="Bloom radius" value={finish.bloomRadius} min={4} max={120} step={.5} unit=" px" onChange={(bloomRadius) => setFinish({ bloomRadius })} onReset={() => setFinish({ bloomRadius: defaultFinish().bloomRadius })}/><RangeField label="Vignette" value={finish.vignette} min={0} max={100} unit="%" onChange={(vignette) => setFinish({ vignette })} onReset={() => setFinish({ vignette: 0 })}/><p className="inspector-note">One non-destructive finish over the complete composite: soft diffusion, highlight-only bloom, then vignette. Before mode bypasses this stack.</p></section>;
}
