import { RotateCcw, SlidersHorizontal } from 'lucide-react';
import { RangeField } from './RangeField';
import { useEditorStore } from '../store/editorStore';
import { blendModes, defaultAdjustments, type BlendMode } from '../types/editor';

function NumberField({ label, value, step = 1, onChange }: { label: string; value: number; step?: number; onChange: (value: number) => void }) { return <label className="number-field"><span>{label}</span><input type="number" value={Number.isInteger(value) ? value : Number(value.toFixed(2))} step={step} onChange={(event) => onChange(Number(event.currentTarget.value))}/></label>; }
const blendLabels: Record<BlendMode, string> = { 'source-over': 'Normal', multiply: 'Multiply', screen: 'Screen', overlay: 'Overlay', 'soft-light': 'Soft Light', 'hard-light': 'Hard Light', 'color-dodge': 'Color Dodge', 'color-burn': 'Color Burn', darken: 'Darken', lighten: 'Lighten', difference: 'Difference', exclusion: 'Exclusion', hue: 'Hue', saturation: 'Saturation', color: 'Color', luminosity: 'Luminosity' };

export function InspectorPanel() {
  const selectedId = useEditorStore((s) => s.selectedLayerId), layer = useEditorStore((s) => s.layers.find((l) => l.id === s.selectedLayerId)), documentModel = useEditorStore((s) => s.document);
  const patchLayer = useEditorStore((s) => s.patchLayer), patchTransform = useEditorStore((s) => s.patchLayerTransform), patchAdjustments = useEditorStore((s) => s.patchLayerAdjustments), resetAdjustment = useEditorStore((s) => s.resetAdjustment), resetLayerValues = useEditorStore((s) => s.resetLayerValues), setDocument = useEditorStore((s) => s.setDocument);
  const adjustment = (key: keyof ReturnType<typeof defaultAdjustments>, label: string, min: number, max: number, step = 1, unit = '') => layer && selectedId ? <RangeField label={label} value={layer.adjustments[key]} min={min} max={max} step={step} unit={unit} onChange={(value) => patchAdjustments(selectedId, { [key]: value })} onReset={() => resetAdjustment(selectedId, key)}/> : null;
  return <aside className="panel panel--inspector"><div className="panel__header"><div><span className="panel__eyebrow">Properties</span><h2>{layer ? 'Layer' : 'Document'}</h2></div><SlidersHorizontal size={18}/></div><div className="inspector-scroll">
    {!layer || !selectedId ? <section className="inspector-section"><h3>Canvas</h3><label className="text-field"><span>Name</span><input value={documentModel.name} onChange={(e) => setDocument({ name: e.currentTarget.value })}/></label><div className="field-grid field-grid--two"><NumberField label="Width" value={documentModel.width} onChange={(width) => setDocument({ width: Math.max(1, Math.round(width)) })}/><NumberField label="Height" value={documentModel.height} onChange={(height) => setDocument({ height: Math.max(1, Math.round(height)) })}/></div><label className="select-field"><span>Background</span><select value={documentModel.background} onChange={(e) => setDocument({ background: e.currentTarget.value as typeof documentModel.background })}><option value="transparent">Transparent</option><option value="black">Black</option><option value="white">White</option></select></label><p className="inspector-note">Imported pixels remain authoritative. Adjustments are evaluated only for preview and export.</p></section> : <>
      <section className="inspector-section"><div className="section-title-row"><h3>Layer</h3><button className="text-button" type="button" onClick={() => resetLayerValues(selectedId)}><RotateCcw size={13}/>Reset all</button></div><label className="text-field"><span>Name</span><input value={layer.name} onChange={(e) => patchLayer(selectedId, { name: e.currentTarget.value })}/></label><label className="select-field"><span>Blend</span><select value={layer.blendMode} onChange={(e) => patchLayer(selectedId, { blendMode: e.currentTarget.value as BlendMode })}>{blendModes.map((mode) => <option key={mode} value={mode}>{blendLabels[mode]}</option>)}</select></label><RangeField label="Opacity" value={layer.opacity} min={0} max={100} unit="%" onChange={(opacity) => patchLayer(selectedId, { opacity })} onReset={() => patchLayer(selectedId, { opacity: 100 })}/></section>
      <section className="inspector-section"><div className="section-title-row"><h3>Transform</h3><button className="text-button" type="button" onClick={() => patchTransform(selectedId, { x: 0, y: 0, scaleX: 1, scaleY: 1, rotation: 0 })}><RotateCcw size={13}/>Reset</button></div><div className="field-grid field-grid--two"><NumberField label="X" value={layer.transform.x} onChange={(x) => patchTransform(selectedId, { x })}/><NumberField label="Y" value={layer.transform.y} onChange={(y) => patchTransform(selectedId, { y })}/><NumberField label="Scale X %" value={layer.transform.scaleX * 100} step={0.1} onChange={(v) => patchTransform(selectedId, { scaleX: Math.max(.001, v / 100) })}/><NumberField label="Scale Y %" value={layer.transform.scaleY * 100} step={0.1} onChange={(v) => patchTransform(selectedId, { scaleY: Math.max(.001, v / 100) })}/></div><NumberField label="Rotation °" value={layer.transform.rotation} step={0.1} onChange={(rotation) => patchTransform(selectedId, { rotation })}/></section>
      <section className="inspector-section"><div className="section-title-row"><h3>Color match</h3><button className="text-button" type="button" onClick={() => patchAdjustments(selectedId, defaultAdjustments())}><RotateCcw size={13}/>Reset</button></div>{adjustment('exposure','Exposure',-3,3,.1,' EV')}{adjustment('contrast','Contrast',-100,100)}{adjustment('saturation','Saturation',-100,100)}{adjustment('temperature','Temperature',-100,100)}{adjustment('tint','Tint',-100,100)}{adjustment('blur','Blur',0,40,.5,' px')}</section>
    </>}
  </div></aside>;
}
