'use client';

import { AlertTriangle, CheckCircle2, LoaderCircle, X } from 'lucide-react';
import { useCallback, useEffect, useRef, useState } from 'react';
import { EditorCanvas } from './components/EditorCanvas';
import { InspectorPanel } from './components/InspectorPanel';
import { LayersPanel } from './components/LayersPanel';
import { TopBar } from './components/TopBar';
import { clearAssets } from './lib/assets';
import { importFiles } from './lib/importers';
import { clearRasterCache, exportPng } from './lib/renderer';
import { clearAutosave, downloadProject, loadAutosave, readProject, saveAutosave } from './lib/storage';
import { useEditorStore } from './store/editorStore';

export default function App() {
  const imageInput = useRef<HTMLInputElement>(null), projectInput = useRef<HTMLInputElement>(null), autosaveReady = useRef(false), autosaveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [fitSignal, setFitSignal] = useState(0), [saved, setSaved] = useState(false);
  const documentModel = useEditorStore((s) => s.document), layers = useEditorStore((s) => s.layers), message = useEditorStore((s) => s.message), error = useEditorStore((s) => s.error), importing = useEditorStore((s) => s.isImporting), restoring = useEditorStore((s) => s.isRestoring);
  const rasterLayerCount = layers.filter((layer) => layer.kind !== 'group').length;
  const replaceProject = useEditorStore((s) => s.replaceProject), appendLayers = useEditorStore((s) => s.appendLayers), resetProject = useEditorStore((s) => s.resetProject), setImporting = useEditorStore((s) => s.setImporting), setRestoring = useEditorStore((s) => s.setRestoring), setMessage = useEditorStore((s) => s.setMessage), setError = useEditorStore((s) => s.setError);
  useEffect(() => { let cancelled = false; void (async () => { try { const project = await loadAutosave(); if (!cancelled && project?.layers.length) { replaceProject(project.document, project.layers, false); setMessage('Autosave restored'); setFitSignal((v) => v + 1); } } catch (cause) { if (!cancelled) setError(cause instanceof Error ? cause.message : 'Autosave restore failed.'); } finally { if (!cancelled) { autosaveReady.current = true; setRestoring(false); } } })(); return () => { cancelled = true; }; }, [replaceProject, setError, setMessage, setRestoring]);
  useEffect(() => { if (!autosaveReady.current || restoring) return; if (autosaveTimer.current) clearTimeout(autosaveTimer.current); autosaveTimer.current = setTimeout(() => { if (!layers.length) return; void saveAutosave({ document: documentModel, layers }).then(() => { setSaved(true); setTimeout(() => setSaved(false), 1600); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Autosave failed.')); }, 700); return () => { if (autosaveTimer.current) clearTimeout(autosaveTimer.current); }; }, [documentModel, layers, restoring, setError]);
  const handleFiles = useCallback(async (files: File[]) => { if (!files.length) return; setImporting(true); setError(null); setMessage('Reading local files…'); try { const state = useEditorStore.getState(), results = await importFiles(files, state.document, state.layers.some((layer) => layer.kind !== 'group')); for (const result of results) { if (result.shouldReplaceProject && result.document) replaceProject(result.document, result.layers); else appendLayers(result.layers); } setFitSignal((v) => v + 1); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Import failed.'); setMessage('Import failed'); } finally { setImporting(false); } }, [appendLayers, replaceProject, setError, setImporting, setMessage]);
  const handleProject = async (file?: File) => { if (!file) return; setImporting(true); setError(null); setMessage('Opening project…'); try { const project = await readProject(file); replaceProject(project.document, project.layers); setFitSignal((v) => v + 1); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Project load failed.'); } finally { setImporting(false); } };
  const handleNew = async () => { if (layers.length && !window.confirm('Discard the current composition? A browser autosave can still be restored until the new project is edited.')) return; clearAssets(); clearRasterCache(); resetProject(); await clearAutosave().catch(() => undefined); setFitSignal((v) => v + 1); };
  const handleSave = async () => { try { setMessage('Saving local project…'); await downloadProject({ document: documentModel, layers }); setMessage('Project saved'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Project save failed.'); } };
  const handleExport = async () => { try { setMessage('Rendering full-resolution 300 DPI PNG…'); await exportPng(documentModel, layers); setMessage(`Exported ${documentModel.width} × ${documentModel.height} PNG · 300 DPI`); } catch (cause) { setError(cause instanceof Error ? cause.message : 'PNG export failed.'); } };
  return <div className="app-shell"><TopBar onNew={() => void handleNew()} onImport={() => imageInput.current?.click()} onOpenProject={() => projectInput.current?.click()} onSaveProject={() => void handleSave()} onExport={() => void handleExport()} onFit={() => setFitSignal((v) => v + 1)}/><div className="workspace"><LayersPanel onImport={() => imageInput.current?.click()}/><EditorCanvas fitSignal={fitSignal} onFiles={handleFiles} onImport={() => imageInput.current?.click()} onSaveProject={() => void handleSave()} onOpenProject={() => projectInput.current?.click()}/><InspectorPanel/></div><footer className="statusbar"><span>{documentModel.width} × {documentModel.height}px</span><span>{rasterLayerCount} layer{rasterLayerCount === 1 ? '' : 's'}</span><span className="statusbar__message">{message}</span>{saved ? <span className="autosave-state"><CheckCircle2 size={12}/>Autosaved</span> : <span>Canvas 2D · sRGB</span>}</footer>{(importing || restoring) ? <div className="loading-overlay"><LoaderCircle className="spin" size={25}/><strong>{restoring ? 'Restoring autosave…' : 'Reading local files…'}</strong><span>No image is uploaded.</span></div> : null}{error ? <div className="error-toast" role="alert"><AlertTriangle size={18}/><div><strong>Couldn’t complete that action</strong><span>{error}</span></div><button type="button" onClick={() => setError(null)} aria-label="Dismiss error"><X size={16}/></button></div> : null}<input ref={imageInput} className="visually-hidden" type="file" accept=".psd,image/png,image/jpeg,image/webp" multiple onChange={(e) => { void handleFiles(Array.from(e.currentTarget.files ?? [])); e.currentTarget.value = ''; }}/><input ref={projectInput} className="visually-hidden" type="file" accept=".ezcomp,application/json" onChange={(e) => { void handleProject(e.currentTarget.files?.[0]); e.currentTarget.value = ''; }}/></div>;
}
